import {
  BookOpen,
  CalendarCheck,
  ClipboardCheck,
  CreditCard,
  GraduationCap,
  LayoutDashboard,
  Users,
} from "lucide-react";
import { date, itemLabel, userName } from "../utils/formatters";

export const numericFields = new Set([
    "rollNumber",
    "experience",
    "salary",
    "creditHours",
    "totalMarks",
    "passingMarks",
    "obtainedMarks",
    "amount",
  ]),
  optionalFields = new Set([
    "experience",
    "creditHours",
    "grade",
    "remarks",
    "paidDate",
    "classTeacher",
    "password", // required on create, but leave blank on edit to keep the current one
    "isActive",
    "phone",
  ]),
  linkedResources = {
    classTeacher: "teachers",
    teacher: "teachers",
    student: "students",
    class: "classes",
    subject: "subjects",
    exam: "exams",
  };

export const selectOptions = {
  gender: ["Male", "Female", "Other"],
  paymentMethod: ["Cash", "Card", "Bank Transfer", "Online"],
  role: ["admin", "teacher", "student"],
  isActive: ["true", "false"],
};

const c = (label, icon, path, key, roles, fields, cols, extra = {}) => ({
  label,
  icon,
  path,
  key,
  roles,
  fields,
  cols,
  ...extra,
});

export const resources = {
  users: c(
    "Users",
    Users,
    "/admin/users",
    "users",
    ["admin"],
    ["firstName", "lastName", "email", "password", "role", "phone", "isActive"],
    [
      ["Name", (r) => userName(r)],
      ["Email", "email"],
      ["Role", "role"],
      ["Status", (r) => (r.isActive === false ? "Inactive" : "Active")],
    ],
    { search: true },
  ),
  students: c(
    "Students",
    GraduationCap,
    "/students",
    "students",
    ["admin"],
    [
      "firstName",
      "lastName",
      "email",
      "password",
      "phone",
      "admissionNumber",
      "className",
      "section",
      "rollNumber",
      "gender",
      "dateOfBirth",
      "address",
      "guardianName",
      "guardianPhone",
    ],
    [
      ["Student", (r) => userName(r.user)],
      ["Admission", "admissionNumber"],
      ["Class", (r) => `${r.className} · ${r.section}`],
      ["Guardian", "guardianName"],
    ],
    { search: true },
  ),
  teachers: c(
    "Teachers",
    GraduationCap,
    "/teachers",
    "teachers",
    ["admin"],
    [
      "firstName",
      "lastName",
      "email",
      "password",
      "employeeId",
      "department",
      "qualification",
      "experience",
      "phone",
      "address",
      "salary",
    ],
    [
      ["Teacher", (r) => userName(r.user)],
      ["Employee ID", "employeeId"],
      ["Department", "department"],
      ["Phone", "phone"],
    ],
    { search: true },
  ),
  classes: c(
    "Classes",
    LayoutDashboard,
    "/classes",
    "classes",
    ["admin"],
    ["className", "section", "academicYear", "classTeacher"],
    [
      ["Class", (r) => `${r.className} · ${r.section}`],
      ["Academic year", "academicYear"],
      ["Teacher", (r) => itemLabel(r.classTeacher)],
      ["Students", (r) => r.students?.length || 0],
    ],
    { singular: "Class" },
  ),
  subjects: c(
    "Subjects",
    BookOpen,
    "/subjects",
    "subjects",
    ["admin"],
    ["subjectCode", "subjectName", "class", "teacher", "creditHours"],
    [
      ["Code", "subjectCode"],
      ["Subject", "subjectName"],
      ["Class", (r) => itemLabel(r.class)],
      ["Credits", "creditHours"],
    ],
  ),
  attendance: c(
    "Attendance",
    CalendarCheck,
    "/attendance",
    "attendance",
    ["admin", "teacher"],
    ["student", "class", "subject", "teacher", "date", "status"],
    [
      ["Student", (r) => itemLabel(r.student)],
      ["Date", (r) => date(r.date)],
      ["Subject", (r) => itemLabel(r.subject)],
      ["Status", "status"],
    ],
    { singular: "Attendance", options: { status: ["Present", "Absent", "Late"] } },
  ),
  exams: c(
    "Exams",
    ClipboardCheck,
    "/exams",
    "exams",
    ["admin", "teacher"],
    ["examName", "class", "subject", "examDate", "totalMarks", "passingMarks"],
    [
      ["Exam", "examName"],
      ["Date", (r) => date(r.examDate)],
      ["Subject", (r) => itemLabel(r.subject)],
      ["Marks", (r) => `${r.passingMarks} / ${r.totalMarks}`],
    ],
    { writeRoles: ["admin"] },
  ),
  results: c(
    "Results",
    ClipboardCheck,
    "/results",
    "results",
    ["admin", "teacher"],
    ["student", "exam", "subject", "obtainedMarks", "grade", "remarks"],
    [
      ["Student", (r) => itemLabel(r.student)],
      ["Exam", (r) => itemLabel(r.exam)],
      ["Subject", (r) => itemLabel(r.subject)],
      ["Marks", "obtainedMarks"],
      ["Grade", "grade"],
    ],
    { deleteRoles: ["admin"] },
  ),
  fees: c(
    "Fees",
    CreditCard,
    "/fees",
    "fees",
    ["admin"],
    ["student", "amount", "dueDate", "paidDate", "status", "paymentMethod"],
    [
      ["Student", (r) => itemLabel(r.student)],
      ["Amount", (r) => `Rs. ${Number(r.amount || 0).toLocaleString()}`],
      ["Due date", (r) => date(r.dueDate)],
      ["Status", "status"],
      ["Method", "paymentMethod"],
    ],
    { options: { status: ["Pending", "Paid", "Overdue"] } },
  ),
};
